apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: scalepolicy-webhook
webhooks:
  - name: scalepolicy.kubehalo.sh
    rules:
      - apiGroups: ["kubehalo.sh"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["scalepolicies"]
    clientConfig:
      service:
        name: kubehalo-webhook
        namespace: default
        path: "/validate"
      caBundle: <BASE64_CA_CERT>
    admissionReviewVersions: ["v1"]
    sideEffects: None
