apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scalepolicies.kubehalo.sh
spec:
  group: kubehalo.sh
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetDeployment:
                  type: string
                targetNamespace:
                  type: string
                metricQuery:
                  type: string
                thresholds:
                  type: object
                  properties:
                    scaleUp:
                      type: number
                    scaleDown:
                      type: number
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: scalepolicies
    singular: scalepolicy
    kind: ScalePolicy
    shortNames:
      - sp
